from pathlib import Path
from html import escape
import json

BASE = "https://urbanartsnews.com"
IMAGE = "/assets/images/barcelona/mark-rox-urban-art-astronaut-bas-museum-barcelona.jpg"

# Deliberately curated translations: these are indexable local pages, not machine-translation redirects.
LANGUAGES = {
    "en": {"name":"English","slug":"street-art-galleries-barcelona","title":"Street Art Galleries Barcelona | Artevistas, BienCuadrado & BAS","h1":"Street Art Galleries Barcelona","intro":"Discover three essential spaces for street, urban and contemporary art in Barcelona: Artevistas, BienCuadrado and BAS Barcelona Art Street Museum.","about":"This independent guide connects galleries, artists, exhibitions and exact visitor information. Each venue includes its official website, address, map and geographic coordinates.","gallery":"Gallery","industry":"Industry","artists":"Artists","tags":"Tags","map":"View on Google Maps","visit":"Official website","published":"Published by Urban Arts News","related":"Explore urban art in Barcelona"},
    "ca": {"name":"Català","slug":"galeries-art-urba-barcelona","title":"Galeries d’art urbà a Barcelona | Artevistas, BienCuadrado i BAS","h1":"Galeries d’art urbà a Barcelona","intro":"Descobreix tres espais essencials d’art de carrer, urbà i contemporani a Barcelona: Artevistas, BienCuadrado i el BAS Barcelona Art Street Museum.","about":"Aquesta guia independent relaciona galeries, artistes, exposicions i informació exacta per a la visita. Cada espai inclou web oficial, adreça, mapa i coordenades geogràfiques.","gallery":"Galeria","industry":"Sector","artists":"Artistes","tags":"Etiquetes","map":"Veure a Google Maps","visit":"Web oficial","published":"Publicat per Urban Arts News","related":"Explora l’art urbà a Barcelona"},
    "es": {"name":"Español","slug":"galerias-arte-urbano-barcelona","title":"Galerías de arte urbano en Barcelona | Artevistas, BienCuadrado y BAS","h1":"Galerías de arte urbano en Barcelona","intro":"Descubre tres espacios esenciales de arte callejero, urbano y contemporáneo en Barcelona: Artevistas, BienCuadrado y BAS Barcelona Art Street Museum.","about":"Esta guía independiente conecta galerías, artistas, exposiciones e información precisa para la visita. Cada espacio incluye su web oficial, dirección, mapa y coordenadas geográficas.","gallery":"Galería","industry":"Sector","artists":"Artistas","tags":"Etiquetas","map":"Ver en Google Maps","visit":"Web oficial","published":"Publicado por Urban Arts News","related":"Explora el arte urbano en Barcelona"},
    "de": {"name":"Deutsch","slug":"street-art-galerien-barcelona","title":"Street-Art-Galerien Barcelona | Artevistas, BienCuadrado und BAS","h1":"Street-Art-Galerien in Barcelona","intro":"Entdecke drei wichtige Orte für Street Art, Urban Art und zeitgenössische Kunst in Barcelona: Artevistas, BienCuadrado und das BAS Barcelona Art Street Museum.","about":"Dieser unabhängige Guide verbindet Galerien, Künstler, Ausstellungen und genaue Besucherinformationen. Zu jedem Ort findest du die offizielle Website, Adresse, Karte und geografische Koordinaten.","gallery":"Galerie","industry":"Branche","artists":"Künstler","tags":"Tags","map":"Auf Google Maps ansehen","visit":"Offizielle Website","published":"Veröffentlicht von Urban Arts News","related":"Urban Art in Barcelona entdecken"},
    "fr": {"name":"Français","slug":"galeries-art-urbain-barcelone","title":"Galeries d’art urbain à Barcelone | Artevistas, BienCuadrado et BAS","h1":"Galeries d’art urbain à Barcelone","intro":"Découvrez trois lieux essentiels dédiés au street art, à l’art urbain et à l’art contemporain à Barcelone : Artevistas, BienCuadrado et le BAS Barcelona Art Street Museum.","about":"Ce guide indépendant relie galeries, artistes, expositions et informations précises pour la visite. Chaque lieu comprend son site officiel, son adresse, sa carte et ses coordonnées géographiques.","gallery":"Galerie","industry":"Secteur","artists":"Artistes","tags":"Mots-clés","map":"Voir sur Google Maps","visit":"Site officiel","published":"Publié par Urban Arts News","related":"Explorer l’art urbain à Barcelone"},
    "it": {"name":"Italiano","slug":"gallerie-arte-urbana-barcellona","title":"Gallerie di arte urbana a Barcellona | Artevistas, BienCuadrado e BAS","h1":"Gallerie di arte urbana a Barcellona","intro":"Scopri tre spazi essenziali dedicati alla street art, all’arte urbana e contemporanea a Barcellona: Artevistas, BienCuadrado e il BAS Barcelona Art Street Museum.","about":"Questa guida indipendente collega gallerie, artisti, mostre e informazioni precise per la visita. Ogni spazio include sito ufficiale, indirizzo, mappa e coordinate geografiche.","gallery":"Galleria","industry":"Settore","artists":"Artisti","tags":"Tag","map":"Vedi su Google Maps","visit":"Sito ufficiale","published":"Pubblicato da Urban Arts News","related":"Esplora l’arte urbana a Barcellona"},
    "pt": {"name":"Português","slug":"galerias-arte-urbana-barcelona","title":"Galerias de arte urbana em Barcelona | Artevistas, BienCuadrado e BAS","h1":"Galerias de arte urbana em Barcelona","intro":"Descubra três espaços essenciais de street art, arte urbana e contemporânea em Barcelona: Artevistas, BienCuadrado e o BAS Barcelona Art Street Museum.","about":"Este guia independente liga galerias, artistas, exposições e informações exatas para a visita. Cada espaço inclui o site oficial, endereço, mapa e coordenadas geográficas.","gallery":"Galeria","industry":"Setor","artists":"Artistas","tags":"Etiquetas","map":"Ver no Google Maps","visit":"Site oficial","published":"Publicado por Urban Arts News","related":"Explorar a arte urbana em Barcelona"},
    "nl": {"name":"Nederlands","slug":"street-art-galeries-barcelona","title":"Streetartgaleries in Barcelona | Artevistas, BienCuadrado en BAS","h1":"Streetartgaleries in Barcelona","intro":"Ontdek drie belangrijke locaties voor streetart, urban art en hedendaagse kunst in Barcelona: Artevistas, BienCuadrado en het BAS Barcelona Art Street Museum.","about":"Deze onafhankelijke gids verbindt galeries, kunstenaars, tentoonstellingen en nauwkeurige bezoekersinformatie. Elke locatie bevat de officiële website, het adres, de kaart en geografische coördinaten.","gallery":"Galerie","industry":"Branche","artists":"Kunstenaars","tags":"Tags","map":"Bekijk op Google Maps","visit":"Officiële website","published":"Gepubliceerd door Urban Arts News","related":"Ontdek urban art in Barcelona"},
    "sv": {"name":"Svenska","slug":"gatukonstgallerier-barcelona","title":"Gatukonstgallerier i Barcelona | Artevistas, BienCuadrado och BAS","h1":"Gatukonstgallerier i Barcelona","intro":"Upptäck tre viktiga platser för gatukonst, urban konst och samtidskonst i Barcelona: Artevistas, BienCuadrado och BAS Barcelona Art Street Museum.","about":"Den här oberoende guiden kopplar samman gallerier, konstnärer, utställningar och exakt besöksinformation. Varje plats har officiell webbplats, adress, karta och geografiska koordinater.","gallery":"Galleri","industry":"Bransch","artists":"Konstnärer","tags":"Taggar","map":"Visa på Google Maps","visit":"Officiell webbplats","published":"Publicerad av Urban Arts News","related":"Utforska urban konst i Barcelona"},
    "ja": {"name":"日本語","slug":"baruserona-urban-art-gallery","title":"バルセロナのアーバンアートギャラリー | Artevistas・BienCuadrado・BAS","h1":"バルセロナのアーバンアートギャラリー","intro":"バルセロナでストリートアート、アーバンアート、現代美術を紹介する重要な3施設、Artevistas、BienCuadrado、BAS Barcelona Art Street Museumをご案内します。","about":"この独立ガイドでは、ギャラリー、アーティスト、展覧会、正確な訪問情報をまとめています。各施設の公式サイト、住所、地図、位置座標を掲載しています。","gallery":"ギャラリー","industry":"分野","artists":"アーティスト","tags":"タグ","map":"Googleマップで見る","visit":"公式サイト","published":"Urban Arts News 掲載","related":"バルセロナのアーバンアートを探す"},
    "ar": {"name":"العربية","slug":"معارض-الفن-الحضري-برشلونة","title":"معارض الفن الحضري في برشلونة | Artevistas وBienCuadrado وBAS","h1":"معارض الفن الحضري في برشلونة","intro":"اكتشف ثلاثة فضاءات أساسية لفن الشارع والفن الحضري والمعاصر في برشلونة: Artevistas وBienCuadrado ومتحف BAS Barcelona Art Street.","about":"يربط هذا الدليل المستقل بين المعارض والفنانين والمعارض الفنية ومعلومات الزيارة الدقيقة. يتضمن كل مكان موقعه الرسمي وعنوانه وخريطته وإحداثياته الجغرافية.","gallery":"المعرض","industry":"القطاع","artists":"الفنانون","tags":"الوسوم","map":"عرض على خرائط Google","visit":"الموقع الرسمي","published":"نشرته Urban Arts News","related":"استكشف الفن الحضري في برشلونة"},
    "el": {"name":"Ελληνικά","slug":"gkaleri-astikis-technis-varkeloni","title":"Γκαλερί αστικής τέχνης στη Βαρκελώνη | Artevistas, BienCuadrado και BAS","h1":"Γκαλερί αστικής τέχνης στη Βαρκελώνη","intro":"Ανακαλύψτε τρεις σημαντικούς χώρους street art, αστικής και σύγχρονης τέχνης στη Βαρκελώνη: Artevistas, BienCuadrado και BAS Barcelona Art Street Museum.","about":"Αυτός ο ανεξάρτητος οδηγός συνδέει γκαλερί, καλλιτέχνες, εκθέσεις και ακριβείς πληροφορίες επίσκεψης. Κάθε χώρος περιλαμβάνει επίσημη ιστοσελίδα, διεύθυνση, χάρτη και γεωγραφικές συντεταγμένες.","gallery":"Γκαλερί","industry":"Κλάδος","artists":"Καλλιτέχνες","tags":"Ετικέτες","map":"Προβολή στο Google Maps","visit":"Επίσημη ιστοσελίδα","published":"Δημοσίευση Urban Arts News","related":"Εξερευνήστε την αστική τέχνη στη Βαρκελώνη"},
    "ko": {"name":"한국어","slug":"bareusellona-dosi-misul-gaelleori","title":"바르셀로나 어반 아트 갤러리 | Artevistas, BienCuadrado, BAS","h1":"바르셀로나 어반 아트 갤러리","intro":"바르셀로나의 스트리트 아트, 어반 아트, 현대미술을 만날 수 있는 세 곳 Artevistas, BienCuadrado, BAS Barcelona Art Street Museum을 소개합니다.","about":"이 독립 가이드는 갤러리, 작가, 전시와 정확한 방문 정보를 연결합니다. 각 장소의 공식 웹사이트, 주소, 지도, 지리 좌표를 제공합니다.","gallery":"갤러리","industry":"분야","artists":"작가","tags":"태그","map":"Google 지도에서 보기","visit":"공식 웹사이트","published":"Urban Arts News 게시","related":"바르셀로나 어반 아트 탐색"},
    "pl": {"name":"Polski","slug":"galerie-sztuki-miejskiej-barcelona","title":"Galerie sztuki miejskiej w Barcelonie | Artevistas, BienCuadrado i BAS","h1":"Galerie sztuki miejskiej w Barcelonie","intro":"Poznaj trzy ważne miejsca prezentujące street art, sztukę miejską i współczesną w Barcelonie: Artevistas, BienCuadrado oraz BAS Barcelona Art Street Museum.","about":"Ten niezależny przewodnik łączy galerie, artystów, wystawy i dokładne informacje dla odwiedzających. Każde miejsce ma oficjalną stronę, adres, mapę i współrzędne geograficzne.","gallery":"Galeria","industry":"Branża","artists":"Artyści","tags":"Tagi","map":"Zobacz w Google Maps","visit":"Oficjalna strona","published":"Opublikowane przez Urban Arts News","related":"Odkryj sztukę miejską w Barcelonie"},
    "tr": {"name":"Türkçe","slug":"barselona-kentsel-sanat-galerileri","title":"Barselona kentsel sanat galerileri | Artevistas, BienCuadrado ve BAS","h1":"Barselona kentsel sanat galerileri","intro":"Barselona’da sokak sanatı, kentsel sanat ve çağdaş sanata ayrılmış üç önemli mekânı keşfedin: Artevistas, BienCuadrado ve BAS Barcelona Art Street Museum.","about":"Bu bağımsız rehber galerileri, sanatçıları, sergileri ve doğru ziyaret bilgilerini bir araya getirir. Her mekân için resmî web sitesi, adres, harita ve coğrafi koordinatlar sunulur.","gallery":"Galeri","industry":"Sektör","artists":"Sanatçılar","tags":"Etiketler","map":"Google Maps’te görüntüle","visit":"Resmî web sitesi","published":"Urban Arts News tarafından yayımlandı","related":"Barselona kentsel sanatını keşfet"},
    "zh-hans": {"name":"简体中文","slug":"巴塞罗那城市艺术画廊","title":"巴塞罗那城市艺术画廊 | Artevistas、BienCuadrado 与 BAS","h1":"巴塞罗那城市艺术画廊","intro":"探索巴塞罗那三个重要的街头艺术、城市艺术与当代艺术空间：Artevistas、BienCuadrado 和 BAS Barcelona Art Street Museum。","about":"这份独立指南连接画廊、艺术家、展览和准确的参观信息。每个场所均提供官方网站、地址、地图和地理坐标。","gallery":"画廊","industry":"类别","artists":"艺术家","tags":"标签","map":"在 Google 地图中查看","visit":"官方网站","published":"由 Urban Arts News 发布","related":"探索巴塞罗那城市艺术"},
    "ru": {"name":"Русский","slug":"galerei-gorodskogo-iskusstva-barselona","title":"Галереи городского искусства в Барселоне | Artevistas, BienCuadrado и BAS","h1":"Галереи городского искусства в Барселоне","intro":"Откройте три важных пространства уличного, городского и современного искусства в Барселоне: Artevistas, BienCuadrado и BAS Barcelona Art Street Museum.","about":"Этот независимый гид объединяет галереи, художников, выставки и точную информацию для посетителей. Для каждого места указаны официальный сайт, адрес, карта и географические координаты.","gallery":"Галерея","industry":"Сфера","artists":"Художники","tags":"Теги","map":"Открыть в Google Maps","visit":"Официальный сайт","published":"Опубликовано Urban Arts News","related":"Исследовать городское искусство Барселоны"},
    "da": {"name":"Dansk","slug":"gadekunstgallerier-barcelona","title":"Gadekunstgallerier i Barcelona | Artevistas, BienCuadrado og BAS","h1":"Gadekunstgallerier i Barcelona","intro":"Oplev tre vigtige steder for gadekunst, urban kunst og samtidskunst i Barcelona: Artevistas, BienCuadrado og BAS Barcelona Art Street Museum.","about":"Denne uafhængige guide forbinder gallerier, kunstnere, udstillinger og præcise besøgsoplysninger. Hvert sted har officiel hjemmeside, adresse, kort og geografiske koordinater.","gallery":"Galleri","industry":"Branche","artists":"Kunstnere","tags":"Tags","map":"Se på Google Maps","visit":"Officiel hjemmeside","published":"Udgivet af Urban Arts News","related":"Udforsk urban kunst i Barcelona"},
    "no": {"name":"Norsk","slug":"gatekunstgallerier-barcelona","title":"Gatekunstgallerier i Barcelona | Artevistas, BienCuadrado og BAS","h1":"Gatekunstgallerier i Barcelona","intro":"Oppdag tre viktige steder for gatekunst, urban kunst og samtidskunst i Barcelona: Artevistas, BienCuadrado og BAS Barcelona Art Street Museum.","about":"Denne uavhengige guiden knytter sammen gallerier, kunstnere, utstillinger og presis besøksinformasjon. Hvert sted har offisiell nettside, adresse, kart og geografiske koordinater.","gallery":"Galleri","industry":"Bransje","artists":"Kunstnere","tags":"Tagger","map":"Se på Google Maps","visit":"Offisiell nettside","published":"Publisert av Urban Arts News","related":"Utforsk urban kunst i Barcelona"},
}

VENUES = [
 {"id":"artevistas","name":"Artevistas Gallery Barcelona","type":"Urban & Contemporary Art Gallery","address":"Passatge del Crèdit 4, 08002 Barcelona · Carrer de la Barra de Ferro 8, 08003 Barcelona","gps":"41.38185, 2.17644 · 41.3849551, 2.1804722","map":"https://www.google.com/maps/search/?api=1&query=Artevistas%20Gallery%20Barcelona","site":"https://www.artevistas.eu/","artists":"MARK ROX, Tim Marsh, Segi Muñoz, Kiara Cortez, Akore, Juan Manuel Pajares, Martí Roca Balcells, Andrzej Farfulowski","tags":"street art · urban art · contemporary art · original works · editions · El Born · Gòtic"},
 {"id":"biencuadrado","name":"BienCuadrado Barcelona","type":"Urban & New Contemporary Art Gallery · Artist Studios · Project Space","address":"Carrer d'Ataülf 14, 08002 Barcelona","gps":"41.3809952, 2.1790367","map":"https://www.google.com/maps/search/?api=1&query=41.3809952%2C2.1790367","site":"https://www.biencuadrado.com/","artists":"Ashwan, Matt Duffin, Rithika Merchant, Dai, Aidan McGovern, Richard Ashcroft","tags":"urban art · new contemporary art · artist studios · exhibitions · project space · Barcelona Gòtic"},
 {"id":"bas-museum","name":"BAS Barcelona Art Street Museum","type":"Urban Art Museum · Cultural Institution · Contemporary Art Exhibitions","address":"Carrer de la Carabassa 10, Ciutat Vella, 08002 Barcelona","gps":"41.379861, 2.179157","map":"https://www.google.com/maps/search/?api=1&query=41.379861%2C2.179157","site":"https://www.basmuseum.com/en/","artists":"MARK ROX, Okuda San Miguel, Aryz, Escif, Dulk, Mina Hamada, Kenor, Felipe Pantone, PichiAvo, Seth, Vhils, Bordalo II, Sixe Paredes, Os Gêmeos","tags":"BAS Museum · Barcelona street art · urban art museum · graffiti · contemporary art · cultural projects · art education · Ciutat Vella"},
]

CSS = """*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;background:#f4f4f2;color:#161616;line-height:1.65}a{color:inherit}.top{background:#090909;color:#fff;padding:18px 5%;display:flex;justify-content:space-between;gap:20px;align-items:center}.logo{font-size:26px;font-weight:900;text-decoration:none}.logo span,.accent{color:#ff5b21}.langs{display:flex;flex-wrap:wrap;gap:10px}.langs a{font-size:12px;color:#fff}.hero{background:#111;color:#fff;padding:72px 6%}.hero h1{font-size:clamp(40px,7vw,78px);line-height:1;margin:0 0 20px;text-transform:uppercase}.hero p{max-width:900px;font-size:19px;color:#ddd}.wrap{width:min(1180px,92%);margin:48px auto}.intro{max-width:900px;font-size:18px}.card{background:#fff;border-top:5px solid #ff5b21;padding:32px;margin:30px 0;box-shadow:0 10px 28px #00000012}.facts{display:flex;flex-wrap:wrap;gap:9px;margin:18px 0}.fact{background:#eee;padding:8px 11px;font-weight:700;font-size:13px}.buttons{display:flex;flex-wrap:wrap;gap:10px}.button{background:#ff5b21;color:#fff;padding:11px 15px;text-decoration:none;font-weight:800}.hero-image{width:100%;height:auto;display:block;margin:35px 0 8px}.credit{font-size:13px;color:#555}.related{background:#111;color:#fff;padding:30px;margin-top:36px}footer{background:#090909;color:#aaa;padding:38px 6%;text-align:center}@media(max-width:700px){.top{align-items:flex-start;flex-direction:column}}"""

def url(code):
    return f"{BASE}/street-art-galleries-barcelona/" if code == "en" else f"{BASE}/{code}/{LANGUAGES[code]['slug']}/"

def alternates():
    links = [f'<link rel="alternate" hreflang="x-default" href="{url("en")}">']
    links += [f'<link rel="alternate" hreflang="{c}" href="{url(c)}">' for c in LANGUAGES]
    return "\n".join(links)

def language_links(active):
    return "".join(f'<a href="{url(c)}" hreflang="{c}" lang="{c}" aria-current="{"page" if c == active else "false"}">{escape(v["name"])}</a>' for c,v in LANGUAGES.items())

def schema(code, item):
    places=[]
    for v in VENUES:
        lat,lon=(v["gps"].split(" · ")[0]).split(", ")
        places.append({"@type":["Museum","ArtGallery"] if v["id"]=="bas-museum" else "ArtGallery","@id":url(code)+"#"+v["id"],"name":v["name"],"url":v["site"],"hasMap":v["map"],"address":v["address"],"geo":{"@type":"GeoCoordinates","latitude":float(lat),"longitude":float(lon)},"keywords":v["tags"]})
    return {"@context":"https://schema.org","@graph":[{"@type":"CollectionPage","@id":url(code)+"#webpage","url":url(code),"name":item["title"],"description":item["intro"],"inLanguage":code,"mainEntity":{"@type":"ItemList","numberOfItems":3,"itemListElement":[{"@type":"ListItem","position":i+1,"name":v["name"],"url":url(code)+"#"+v["id"]} for i,v in enumerate(VENUES)]}},{"@type":"ImageObject","@id":url(code)+"#mark-rox-image","name":"MARK ROX – Urban Art Astronaut at BAS Museum Barcelona","contentUrl":BASE+IMAGE,"caption":"MARK ROX (@pop.art.pov) at BAS Barcelona Art Street Museum","creator":{"@type":"Person","name":"MARK ROX","sameAs":"https://www.instagram.com/pop.art.pov/"},"contentLocation":{"@id":url(code)+"#bas-museum"},"creditText":"Artwork: MARK ROX (@pop.art.pov). Location: BAS Barcelona Art Street Museum. Editorial use by Urban Arts News.","width":1893,"height":853}]+places}

def render(code,item):
    direction="rtl" if code=="ar" else "ltr"
    cards=[]
    for v in VENUES:
        cards.append(f'''<article class="card" id="{v['id']}"><small>{escape(item['gallery'])}</small><h2>{escape(v['name'])}</h2><p>{escape(item['about'])}</p><div class="facts"><span class="fact">{escape(item['industry'])}: {escape(v['type'])}</span><span class="fact">GPS: {escape(v['gps'])}</span></div><p><strong>{escape(v['address'])}</strong></p><p><strong>{escape(item['artists'])}:</strong> {escape(v['artists'])}</p><p><strong>{escape(item['tags'])}:</strong> {escape(v['tags'])}</p><div class="buttons"><a class="button" href="{v['site']}" target="_blank" rel="noopener">{escape(item['visit'])}</a><a class="button" href="{v['map']}" target="_blank" rel="noopener">{escape(item['map'])}</a><a class="button" href="{url(code)}#{v['id']}">{escape(item['published'])}</a></div></article>''')
    image=f'''<figure><picture><source type="image/webp" srcset="/assets/images/barcelona/mark-rox-urban-art-astronaut-bas-museum-barcelona.webp"><img class="hero-image" src="{IMAGE}" alt="MARK ROX urban art astronaut at BAS Barcelona Art Street Museum" width="1893" height="853" loading="eager" fetchpriority="high"></picture><figcaption class="credit">Artwork: <a href="https://www.instagram.com/pop.art.pov/" target="_blank" rel="noopener"><strong>MARK ROX · @pop.art.pov</strong></a> · BAS Barcelona Art Street Museum · Carrer de la Carabassa 10 · GPS 41.379861, 2.179157.</figcaption></figure>'''
    canonical=url(code)
    return f'''<!doctype html><html lang="{code}" dir="{direction}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(item['title'])}</title><meta name="description" content="{escape(item['intro'])}"><meta name="robots" content="index,follow,max-image-preview:large,max-snippet:-1"><link rel="canonical" href="{canonical}">{alternates()}<meta property="og:type" content="website"><meta property="og:site_name" content="Urban Arts News"><meta property="og:title" content="{escape(item['title'])}"><meta property="og:description" content="{escape(item['intro'])}"><meta property="og:url" content="{canonical}"><meta property="og:image" content="{BASE+IMAGE}"><meta property="og:image:width" content="1893"><meta property="og:image:height" content="853"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="{escape(item['title'])}"><meta name="twitter:description" content="{escape(item['intro'])}"><meta name="twitter:image" content="{BASE+IMAGE}"><script type="application/ld+json">{json.dumps(schema(code,item),ensure_ascii=False,separators=(',',':')).replace('</','<\\/')}</script><style>{CSS}</style></head><body><header class="top"><a class="logo" href="/">URBAN <span>ARTS</span> NEWS</a><nav class="langs" aria-label="Languages">{language_links(code)}</nav></header><section class="hero"><h1>{escape(item['h1'])}</h1><p>{escape(item['intro'])}</p></section><main class="wrap"><p class="intro">{escape(item['about'])}</p>{image}{''.join(cards)}<section class="related"><h2>{escape(item['related'])}</h2><p><a class="button" href="/urban-art-city/barcelona/spain/">Barcelona · Urban Arts News</a></p></section></main><footer>© 2026 Urban Arts News · {escape(item['h1'])}</footer></body></html>'''

def main():
    master=Path("street-art-galleries-barcelona/index.html")
    html=master.read_text(encoding="utf-8")
    old="/assets/images/barcelona/street-art-museum-barcelona-bas-visual-identity"
    new="/assets/images/barcelona/mark-rox-urban-art-astronaut-bas-museum-barcelona"
    html=html.replace(old,new)
    html=html.replace("Abstract visual identity of BAS Barcelona Art Street Museum","MARK ROX urban art astronaut at BAS Barcelona Art Street Museum")
    html=html.replace("The expansive BAS visual identity closes the museum gallery with a contemporary graphic gesture rooted in urban culture.","Urban-art astronaut by MARK ROX at BAS Barcelona Art Street Museum. Artist source: @pop.art.pov on Instagram.")
    html=html.replace("BAS Barcelona Art Street Visual Identity","MARK ROX Urban Art Astronaut at BAS Barcelona")
    html=html.replace("Abstract contemporary visual identity of BAS Barcelona Art Street Museum.","Urban-art astronaut by MARK ROX at BAS Barcelona Art Street Museum in Ciutat Vella.")
    html=html.replace('"width":1896,"height":853', '"width":1893,"height":853,"creator":{"@type":"Person","name":"MARK ROX","sameAs":"https://www.instagram.com/pop.art.pov/"},"creditText":"Artwork by MARK ROX (@pop.art.pov); photographed at BAS Barcelona Art Street Museum"',1)
    if 'hreflang="x-default"' not in html:
        html=html.replace('<link rel="canonical" href="https://urbanartsnews.com/street-art-galleries-barcelona/">','<link rel="canonical" href="https://urbanartsnews.com/street-art-galleries-barcelona/">\n'+alternates())
    master.write_text(html,encoding="utf-8")
    for code,item in LANGUAGES.items():
        if code=="en":
            continue
        out=Path(code)/item["slug"]/"index.html"
        out.parent.mkdir(parents=True,exist_ok=True)
        out.write_text(render(code,item),encoding="utf-8")
    sitemap=Path("sitemap.xml")
    text=sitemap.read_text(encoding="utf-8")
    marker="</urlset>"
    additions=[]
    for code in LANGUAGES:
        if code=="en" or f"<loc>{url(code)}</loc>" in text:
            continue
        additions.append(f"<url><loc>{url(code)}</loc><lastmod>2026-09-02</lastmod><changefreq>weekly</changefreq><priority>0.8</priority></url>")
    if additions:
        text=text.replace(marker,"\n".join(additions)+"\n"+marker)
        sitemap.write_text(text,encoding="utf-8")
    print(f"Generated {len(LANGUAGES)-1} localized Barcelona gallery pages")

if __name__=="__main__":
    main()
