"""Generate localized, indexable Ashwan artist profiles."""
from pathlib import Path
from html import escape
import re

BASE="https://urbanartsnews.com"
ORIGINAL=f"{BASE}/artists/ashwan/"
IMAGE="/assets/images/ashwan/ashwan-grey-gold-abstract-letter-work.jpg"
INSTAGRAM="https://www.instagram.com/ashwanarts/"

LANGUAGES={
"ca":("Català","Ashwan: lettering, hip-hop i art urbà contemporani a Barcelona","Ashwan a Barcelona","Artista urbà · Barcelona",[("Qui és Ashwan?","Ashwan és un artista contemporani establert a Barcelona. La seva pràctica connecta la cultura hip-hop, les influències del graffiti, el lettering i les tècniques mixtes. Les lletres no funcionen només com a paraules: es converteixen en formes, ritmes i estructures visuals amb una identitat pròpia."),("Materials i procés creatiu","L’artista treballa sovint amb cartró reutilitzat i altres superfícies quotidianes. Marques, capes, línies i fragments tipogràfics transformen materials modestos en composicions enèrgiques. Aquesta elecció manté una relació directa amb el carrer i amb la cultura urbana de Barcelona."),("Entre el carrer i l’art contemporani","L’obra d’Ashwan no separa estrictament estudi, graffiti i galeria. Combina l’espontaneïtat urbana amb una construcció visual precisa, i pot aparèixer com pintura, collage, instal·lació o escultura tipogràfica. La selecció d’Urban Arts News documenta aquesta evolució."),("Ashwan a Urban Arts News","Aquest perfil reuneix obres escollides, una galeria visual i enllaços al compte oficial de l’artista. També connecta Ashwan amb l’arxiu d’art urbà de Barcelona i amb altres creadors independents de la ciutat.")],"Veure la galeria d’Ashwan","Explorar l’art urbà de Barcelona","Llegir l’article original en anglès"),
"es":("Español","Ashwan: lettering, hip-hop y arte urbano contemporáneo en Barcelona","Ashwan en Barcelona","Artista urbano · Barcelona",[("¿Quién es Ashwan?","Ashwan es un artista contemporáneo afincado en Barcelona. Su práctica conecta cultura hip-hop, influencias del graffiti, lettering y técnicas mixtas. Las letras no funcionan únicamente como palabras: se convierten en formas, ritmos y estructuras visuales con identidad propia."),("Materiales y proceso creativo","El artista trabaja con frecuencia sobre cartón reutilizado y otras superficies cotidianas. Marcas, capas, líneas y fragmentos tipográficos transforman materiales modestos en composiciones enérgicas. Esta elección conserva una relación directa con la calle y la cultura urbana de Barcelona."),("Entre la calle y el arte contemporáneo","La obra de Ashwan no separa estrictamente estudio, graffiti y galería. Combina espontaneidad urbana con una construcción visual precisa y puede aparecer como pintura, collage, instalación o escultura tipográfica. Urban Arts News documenta esta evolución."),("Ashwan en Urban Arts News","Este perfil reúne obras seleccionadas, una galería visual y enlaces a la cuenta oficial del artista. También conecta a Ashwan con el archivo de arte urbano de Barcelona y con otros creadores independientes de la ciudad.")],"Ver la galería de Ashwan","Explorar el arte urbano de Barcelona","Leer el artículo original en inglés"),
"de":("Deutsch","Ashwan: Lettering, Hip-Hop und zeitgenössische Urban Art in Barcelona","Ashwan in Barcelona","Urban Artist · Barcelona",[("Wer ist Ashwan?","Ashwan ist ein in Barcelona lebender zeitgenössischer Künstler. Seine Arbeit verbindet Hip-Hop-Kultur, Einflüsse aus dem Graffiti, Lettering und Mixed Media. Buchstaben dienen dabei nicht nur als Wörter, sondern werden zu Formen, Rhythmen und eigenständigen visuellen Strukturen."),("Materialien und Arbeitsweise","Der Künstler arbeitet häufig auf wiederverwendetem Karton und alltäglichen Oberflächen. Spuren, Schichten, Linien und typografische Fragmente verwandeln einfache Materialien in kraftvolle Kompositionen. Dadurch bleibt seine Arbeit eng mit der Straße und Barcelonas urbaner Kultur verbunden."),("Zwischen Straße und Gegenwartskunst","Ashwans Werk zieht keine harte Grenze zwischen Atelier, Graffiti und Galerie. Urbane Spontaneität trifft auf einen präzisen Bildaufbau; daraus entstehen Malerei, Collage, Installation und typografische Skulpturen. Urban Arts News dokumentiert diese Entwicklung."),("Ashwan bei Urban Arts News","Dieses Profil vereint ausgewählte Werke, eine Bildergalerie und den offiziellen Instagram-Auftritt. Zugleich verbindet es Ashwan mit dem Barcelona-Archiv und weiteren unabhängigen Künstlerinnen und Künstlern der Stadt.")],"Ashwan-Galerie ansehen","Urban Art in Barcelona entdecken","Englischen Originalartikel lesen"),
"fr":("Français","Ashwan : lettering, hip-hop et art urbain contemporain à Barcelone","Ashwan à Barcelone","Artiste urbain · Barcelone",[("Qui est Ashwan ?","Ashwan est un artiste contemporain installé à Barcelone. Sa pratique relie la culture hip-hop, les influences du graffiti, le lettering et les techniques mixtes. Les lettres ne servent pas seulement de mots : elles deviennent des formes, des rythmes et des structures visuelles autonomes."),("Matériaux et processus créatif","L’artiste travaille souvent sur du carton récupéré et des surfaces ordinaires. Traces, couches, lignes et fragments typographiques transforment des matériaux modestes en compositions énergiques. Ce choix maintient un lien direct avec la rue et la culture urbaine barcelonaise."),("Entre rue et art contemporain","L’œuvre d’Ashwan ne sépare pas strictement atelier, graffiti et galerie. Elle associe spontanéité urbaine et construction visuelle précise sous forme de peinture, collage, installation ou sculpture typographique. Urban Arts News en documente l’évolution."),("Ashwan sur Urban Arts News","Ce profil rassemble des œuvres sélectionnées, une galerie et le compte officiel de l’artiste. Il relie également Ashwan aux archives de l’art urbain de Barcelone et aux autres créateurs indépendants de la ville.")],"Voir la galerie Ashwan","Découvrir l’art urbain à Barcelone","Lire l’article original en anglais"),
"it":("Italiano","Ashwan: lettering, hip-hop e arte urbana contemporanea a Barcellona","Ashwan a Barcellona","Artista urbano · Barcellona",[("Chi è Ashwan?","Ashwan è un artista contemporaneo che vive a Barcellona. La sua pratica collega cultura hip-hop, influenze dei graffiti, lettering e tecniche miste. Le lettere non funzionano soltanto come parole, ma diventano forme, ritmi e strutture visive autonome."),("Materiali e processo creativo","L’artista lavora spesso su cartone recuperato e superfici quotidiane. Segni, strati, linee e frammenti tipografici trasformano materiali semplici in composizioni energiche. Questa scelta conserva un rapporto diretto con la strada e la cultura urbana di Barcellona."),("Tra strada e arte contemporanea","Il lavoro di Ashwan non separa rigidamente studio, graffiti e galleria. Unisce spontaneità urbana e costruzione visiva precisa attraverso pittura, collage, installazione e scultura tipografica. Urban Arts News documenta questa evoluzione."),("Ashwan su Urban Arts News","Il profilo riunisce opere selezionate, una galleria visiva e il canale ufficiale dell’artista. Collega inoltre Ashwan all’archivio di arte urbana di Barcellona e agli altri creativi indipendenti della città.")],"Vedi la galleria di Ashwan","Esplora l’arte urbana di Barcellona","Leggi l’articolo originale in inglese"),
"pt":("Português","Ashwan: lettering, hip-hop e arte urbana contemporânea em Barcelona","Ashwan em Barcelona","Artista urbano · Barcelona",[("Quem é Ashwan?","Ashwan é um artista contemporâneo radicado em Barcelona. A sua prática liga cultura hip-hop, influências do graffiti, lettering e técnicas mistas. As letras não funcionam apenas como palavras: tornam-se formas, ritmos e estruturas visuais independentes."),("Materiais e processo criativo","O artista trabalha frequentemente sobre cartão reutilizado e superfícies do quotidiano. Marcas, camadas, linhas e fragmentos tipográficos transformam materiais simples em composições enérgicas. A escolha mantém uma ligação direta com a rua e a cultura urbana de Barcelona."),("Entre a rua e a arte contemporânea","A obra de Ashwan não separa rigidamente estúdio, graffiti e galeria. Combina espontaneidade urbana com construção visual precisa em pintura, colagem, instalação e escultura tipográfica. Urban Arts News documenta esta evolução."),("Ashwan na Urban Arts News","Este perfil reúne obras selecionadas, uma galeria visual e a conta oficial do artista. Também liga Ashwan ao arquivo de arte urbana de Barcelona e a outros criadores independentes da cidade.")],"Ver a galeria de Ashwan","Explorar a arte urbana de Barcelona","Ler o artigo original em inglês"),
"sq":("Shqip","Ashwan: lettering, hip-hop dhe art urban bashkëkohor në Barcelonë","Ashwan në Barcelonë","Artist urban · Barcelonë",[("Kush është Ashwan?","Ashwan është një artist bashkëkohor me bazë në Barcelonë. Praktika e tij lidh kulturën hip-hop, ndikimet e grafitit, lettering-un dhe teknikat e përziera. Shkronjat nuk shërbejnë vetëm si fjalë, por bëhen forma, ritme dhe struktura vizuale të pavarura."),("Materialet dhe procesi krijues","Artisti punon shpesh mbi karton të ripërdorur dhe sipërfaqe të zakonshme. Shenjat, shtresat, vijat dhe fragmentet tipografike i shndërrojnë materialet e thjeshta në kompozime energjike, të lidhura drejtpërdrejt me rrugën dhe kulturën urbane të Barcelonës."),("Midis rrugës dhe artit bashkëkohor","Vepra e Ashwan nuk vendos kufi të prerë midis studios, grafitit dhe galerisë. Ajo bashkon spontanitetin urban me ndërtim të saktë vizual në pikturë, kolazh, instalacion dhe skulpturë tipografike."),("Ashwan në Urban Arts News","Ky profil mbledh vepra të zgjedhura, një galeri pamore dhe llogarinë zyrtare të artistit. Gjithashtu e lidh Ashwan me arkivin e artit urban të Barcelonës dhe krijues të tjerë të pavarur.")],"Shikoni galerinë Ashwan","Eksploroni artin urban të Barcelonës","Lexoni artikullin origjinal në anglisht"),
"ja":("日本語","Ashwan：バルセロナのレタリング、ヒップホップ、現代アーバンアート","バルセロナのAshwan","アーバンアーティスト · バルセロナ",[("Ashwanとは","Ashwanはバルセロナを拠点に活動する現代アーティストです。ヒップホップ文化、グラフィティの影響、レタリング、ミクストメディアを結びつけています。文字は言葉としてだけでなく、独立した形、リズム、視覚的な構造へ変化します。"),("素材と制作方法","再利用した段ボールや日常的な表面に、線、層、痕跡、文字の断片を重ねます。身近な素材が力強い構成へ変わり、バルセロナのストリートと都市文化との直接的な関係が保たれています。"),("ストリートと現代美術の間","Ashwanの作品は、スタジオ、グラフィティ、ギャラリーを厳密に分けません。都市の即興性と精密な構成を組み合わせ、絵画、コラージュ、インスタレーション、文字の彫刻へ展開します。"),("Urban Arts NewsのAshwan","このページでは、選ばれた作品、画像ギャラリー、公式Instagramを紹介します。バルセロナのアーバンアート資料や、街で活動する他の独立系アーティストにもつながります。")],"Ashwanギャラリーを見る","バルセロナのアーバンアートを見る","英語のオリジナル記事を読む"),
"ar":("العربية","أشوان: فن الحروف والهيب هوب والفن الحضري المعاصر في برشلونة","أشوان في برشلونة","فنان حضري · برشلونة",[("من هو أشوان؟","أشوان فنان معاصر يقيم في برشلونة. تجمع ممارسته بين ثقافة الهيب هوب وتأثيرات الغرافيتي وفن الحروف والوسائط المختلطة. لا تعمل الحروف بوصفها كلمات فقط، بل تتحول إلى أشكال وإيقاعات وبنى بصرية مستقلة."),("المواد والعملية الإبداعية","يعمل الفنان كثيراً على الورق المقوى المعاد استخدامه والأسطح اليومية. تحول العلامات والطبقات والخطوط والشظايا الطباعية المواد البسيطة إلى تركيبات حيوية، وتحافظ على صلة مباشرة بالشارع والثقافة الحضرية في برشلونة."),("بين الشارع والفن المعاصر","لا يفصل عمل أشوان بشكل صارم بين الاستوديو والغرافيتي والمعرض. فهو يجمع عفوية الشارع مع بناء بصري دقيق، ويتخذ شكل الرسم والكولاج والتركيب والنحت الطباعي. توثق Urban Arts News هذا التطور."),("أشوان على Urban Arts News","يجمع هذا الملف أعمالاً مختارة ومعرض صور وحساب الفنان الرسمي. كما يربط أشوان بأرشيف الفن الحضري في برشلونة وبمبدعين مستقلين آخرين في المدينة.")],"مشاهدة معرض أشوان","استكشاف الفن الحضري في برشلونة","قراءة المقال الأصلي بالإنجليزية")}

CSS="""*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#171717;line-height:1.7}.top,footer{background:#111;color:#fff;padding:22px max(5vw,24px)}.logo{color:#fff;text-decoration:none;font-size:24px;font-weight:900}.logo span,.eyebrow{color:#ff5b21}.hero{display:grid;grid-template-columns:1.1fr .9fr;background:#eee}.hero-copy{padding:7vw 6vw}.hero h1{font-size:clamp(38px,6vw,76px);line-height:1;margin:12px 0}.hero img{width:100%;height:100%;min-height:430px;object-fit:cover}.wrap{max-width:960px;margin:auto;padding:55px 24px}.article h2{margin-top:42px;font-size:28px}.actions,.language-links{display:flex;flex-wrap:wrap;gap:10px;margin-top:28px}.button,.language-links a{background:#ff5b21;color:#fff;text-decoration:none;padding:10px 14px;font-weight:800}.button.dark,.language-links a{background:#111}.language-links a.active{background:#ff5b21}footer a{color:#fff}@media(max-width:720px){.hero{grid-template-columns:1fr}.hero img{min-height:280px}.wrap{padding-top:30px}}"""

def url(c): return f"{BASE}/{c}/artists/ashwan/"
def alternates():
    links=[f'<link rel="alternate" hreflang="en" href="{ORIGINAL}">',f'<link rel="alternate" hreflang="x-default" href="{ORIGINAL}">']
    links += [f'<link rel="alternate" hreflang="{c}" href="{url(c)}">' for c in LANGUAGES]
    return ''.join(links)
def language_links(active):
    links=[f'<a class="{"active" if active=="en" else ""}" href="{ORIGINAL}" hreflang="en">English</a>']
    links += [f'<a class="{"active" if active==c else ""}" href="/{c}/artists/ashwan/" hreflang="{c}">{escape(v[0])}</a>' for c,v in LANGUAGES.items()]
    return ''.join(links)
def render(c,v):
    name,title,heading,label,sections,gallery,city,original=v; direction=' dir="rtl"' if c=='ar' else ''
    body=''.join(f'<section><h2>{escape(h)}</h2><p>{escape(p)}</p></section>' for h,p in sections)
    desc=sections[0][1]
    return f'''<!DOCTYPE html><html lang="{c}"{direction}><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)} | Urban Arts News</title><meta name="description" content="{escape(desc,quote=True)}"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="{url(c)}">{alternates()}<style>{CSS}</style></head><body><header class="top"><a class="logo" href="/">URBAN <span>ARTS</span> NEWS</a></header><section class="hero"><div class="hero-copy"><div class="eyebrow">{escape(label)}</div><h1>{escape(heading)}</h1><p>{escape(desc)}</p></div><img src="{IMAGE}" alt="Ashwan Barcelona urban art lettering" width="1600" height="1067"></section><main class="wrap"><article class="article">{body}<div class="actions"><a class="button" href="/artists/ashwan/gallery/">{escape(gallery)} →</a><a class="button dark" href="/urban-art-city/barcelona/spain/">{escape(city)} →</a><a class="button dark" href="{INSTAGRAM}" target="_blank" rel="noopener">Instagram →</a><a class="button dark" href="{ORIGINAL}">{escape(original)} →</a></div><section><h2>Ashwan · Languages</h2><div class="language-links">{language_links(c)}</div></section></article></main><footer><a href="/artists/ashwan/">Ashwan</a> · <a href="/artists/">Urban Artists</a> · <a href="/languages/">Languages</a></footer></body></html>'''
def patch_original():
    p=Path('artists/ashwan/index.html'); html=p.read_text(encoding='utf-8')
    html=re.sub(r'\n?<section class="artist-language-versions[^"]*".*?</section>\n?','\n',html,flags=re.I|re.S)
    block=f'<section class="artist-language-versions"><h2>Read this article in another language</h2><div class="language-links">{language_links("en")}</div></section>'
    pos=html.find('<aside class="artist-info">'); end=html.rfind('</div>',0,pos)
    if pos<0 or end<0: raise RuntimeError('Ashwan article ending not found')
    html=html[:end]+block+'\n\n'+html[end:]
    if 'ashwan-language-style' not in html:
        style='<style id="ashwan-language-style">.language-links{display:flex;flex-wrap:wrap;gap:9px;margin-top:18px}.language-links a{background:#111;color:#fff;padding:9px 12px;text-decoration:none;font-weight:800}.language-links a:hover,.language-links a.active{background:#ff5b21}</style>'
        html=html.replace('</head>',alternates()+style+'</head>',1)
    html=re.sub(r'(?m)^[ \t]+$','',html); p.write_text(html,encoding='utf-8')
def main():
    for c,v in LANGUAGES.items():
        p=Path(c)/'artists/ashwan/index.html'; p.parent.mkdir(parents=True,exist_ok=True); p.write_text(render(c,v),encoding='utf-8')
    patch_original(); print('Ashwan language profiles generated: 9 plus English original')
if __name__=='__main__': main()
